services:
  qa-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: "rakhaalif/casecraft-agent:latest"
    env_file:
      - .env
    environment:
      - BOT_FORCE=1
    restart: unless-stopped
